[package]
name = "prefix-tree"
version = "0.2.0"
authors = ["Dominik Miedziński <dominik@mdzn.pl>"]
license = "MIT"
repository = "https://github.com/miedzinski/prefix-tree"
description = "Map and set interface using trie data structure"
keywords = ["prefix", "trie", "radix", "patricia", "tree", "map", "set"]

[dependencies]
